; PlatformIO Project Configuration File

[env:adafruit_feather_esp32s3_nopsram]
platform = espressif32
board = adafruit_feather_esp32s3_nopsram
framework = espidf
monitor_speed = 115200
monitor_raw = yes
build_flags =
    -DCONFIG_MQTT_TRANSPORT_SSL=1
    -DCONFIG_MQTT_PROTOCOL_311=1
